### ISSUE TITLE
Clicking on Sicily map zooms to extent in other map?

### ISSUE THREAD

**Issue by rgdonohue** [courtneysimonse/sicily-immigrants#1]
Currently, if the user has zoomed into the map and then clicks on the Sicily map, it may not have any points there.

But ... maybe that's the point? Like if a user really wants to focus on Chicago and see where people came from .... ?

**Comment by courtneysimonse** [comment]
Yeah, I could go both ways on this. Especially if you are looking at somewhere with a bunch of points like NYC. It would be frustrating to keep zooming in to the same place, I think.
Maybe I could do something where it zooms out if no markers are in view?
