### ISSUE TITLE
improve time slider UI layout

### ISSUE THREAD

**Issue by rgdonohue** [courtneysimonse/sicily-immigrants#4]
The slider feels too wide for me, and a bit difficult to see. Perhaps there can be a more general panel containing this UI element and the other(s) ... and only the width of the US map?

**Comment by rgdonohue** [comment]
Possible solution: https://leaverou.github.io/multirange/

**Comment by courtneysimonse** [comment]
I decided to go with https://refreshless.com/nouislider/ . I have it functional, but need to work on the looks.
